### ISSUE TITLE
access denied to AWS for collections.yml

### ISSUE THREAD

**Issue by flummingbird** [lsulibraries/islandora_ansible#4]
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>A0776B1E6ECB31BC</RequestId>
<HostId>
mkUTlHZl6pb3/p6T4R1tfgaSDKk6W/fbwBFTCzStJs1v1nThI/wpUsbx0Em1xrXsmT3W7SliLIw=
</HostId>
</Error>

**Comment by jpeak5** [comment]
@flummingbird I'm gonna close this one because collection.yml relies on .zips in a bucket that requires LSU ip address:

~~~

            "Resource": "arn:aws:s3:::lsulibraries-sample-collections/*",
            "Condition": {
                "IpAddress": {
                    "aws:SourceIp": [
                        "130.39.0.0/16",
                        "167.96.0.0/16",

~~~
